#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
JOB=$SCRIPT_DIR/health_check_job.py
TESTBED=$SCRIPT_DIR/../lab.yml

pyats run job $JOB --testbed-file $TESTBED --health-checks cpu memory logging core

# --health-remote-device name:myserver_in_testbed path:/tmp/ protocol:http --health-mgmt-vrf iosxe:None