#!/bin/bash

for router in r1 r2 r3 r4 ; do
/usr/bin/env python -m unicon.playback.mock --recorded-data record/$router --output mock/$router/mock_device.yaml
done

for router in r1 r2 r3 r4 ; do
sed --in-place "s/prompt: switch/prompt: $router/g" mock/$router/mock_device.yaml
done
