#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
JOB=$SCRIPT_DIR/mock_job.py
TESTBED=$SCRIPT_DIR/../lab.yml

# WITHOUT RECORD
# pyats run job $JOB --testbed-file $TESTBED

# RECORD
pyats run job $JOB --testbed-file $TESTBED --record record

# REPLAY using recorded data, 4 times faster than real device
# pyats run job $JOB --testbed-file $TESTBED --replay record --speed 4
