#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
JOB=$SCRIPT_DIR/downup_job.py
TESTBED=$SCRIPT_DIR/../lab.yml

# RECORD
# pyats run job $JOB --testbed-file $TESTBED --record record

# REPLAY
# pyats run job $JOB --testbed-file $TESTBED --replay record

# REAL DEVICE
pyats run job $JOB --testbed-file $TESTBED
